# Generated by Django 5.0.4 on 2024-10-10 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100)),
                ('flujo', models.CharField(max_length=10)),
                ('sucursal', models.CharField(max_length=50)),
                ('estadoPedido', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaRecepcion', models.DateTimeField(blank=True, null=True)),
                ('fechaDespacho', models.DateTimeField(blank=True, null=True)),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('lpn', models.CharField(max_length=100, unique=True)),
                ('estadoLpn', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('trackingDistribucion', models.CharField(blank=True, max_length=100, null=True)),
                ('trackingTransporte', models.CharField(blank=True, max_length=100, null=True)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('order_data', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='usersapp.company')),
            ],
        ),
    ]
