# Generated by Django 5.1.3 on 2024-11-16 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingTransporte', models.CharField(max_length=100, unique=True)),
                ('rawJson', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100)),
                ('flujo', models.CharField(max_length=10)),
                ('sucursal', models.CharField(max_length=50)),
                ('estadoPedido', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaRecepcion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('fechaDespacho', models.DateTimeField(blank=True, null=True)),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('lpn', models.CharField(max_length=100, unique=True)),
                ('estadoLpn', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('trackingDistribucion', models.CharField(blank=True, max_length=100, null=True)),
                ('codigoPostaltxt', models.CharField(max_length=10)),
                ('order_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostalCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=4, unique=True)),
                ('localidad', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=50)),
                ('amba_intralog', models.BooleanField(default=False)),
                ('flex', models.BooleanField(default=False)),
                ('dias_limite', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='SRTrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('rawJson', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=25, null=True)),
                ('pedido', models.CharField(blank=True, max_length=25, null=True)),
                ('seller', models.CharField(blank=True, max_length=25, null=True)),
                ('reference', models.CharField(max_length=50)),
                ('checkout_observation', models.CharField(max_length=50)),
                ('planned_date', models.DateField()),
            ],
        ),
    ]
