# Generated by Django 5.1.3 on 2024-11-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataapp', '0001_initial'),
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='usersapp.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='trackingTransporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_transporte', to='dataapp.catrackingdata'),
        ),
        migrations.AddField(
            model_name='order',
            name='codigoPostal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postal_codes', to='dataapp.postalcodes'),
        ),
    ]
