# Generated by Django 5.0.4 on 2024-10-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=4, unique=True)),
                ('localidad', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=50)),
                ('amba_intralog', models.BooleanField(default=False)),
                ('flex', models.BooleanField(default=False)),
            ],
        ),
    ]
