# Generated by Django 5.0.4 on 2024-10-25 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_postalcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='codigoPostaltxt',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postalcodes',
            name='dias_limite',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='codigoPostal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postal_codes', to='dataapp.postalcodes'),
        ),
    ]
