# Generated by Django 5.0.4 on 2024-10-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_order_codigopostaltxt_postalcodes_dias_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingTransporte', models.CharField(default=None, max_length=100, unique=True)),
                ('otherData1', models.CharField(max_length=100)),
                ('otherData2', models.CharField(max_length=100)),
                ('otherData3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SRTrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingDistribucion', models.CharField(max_length=100, unique=True)),
                ('otherData1', models.CharField(max_length=100)),
                ('otherData2', models.CharField(max_length=100)),
                ('otherData3', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='trackingTransporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_transporte', to='dataapp.catrackingdata'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trackingDistribucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_distribucion', to='dataapp.srtrackingdata'),
        ),
    ]
