# Generated by Django 5.0.4 on 2024-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_catrackingdata_srtrackingdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catrackingdata',
            name='otherData1',
        ),
        migrations.RemoveField(
            model_name='catrackingdata',
            name='otherData2',
        ),
        migrations.RemoveField(
            model_name='catrackingdata',
            name='otherData3',
        ),
        migrations.RemoveField(
            model_name='srtrackingdata',
            name='otherData1',
        ),
        migrations.RemoveField(
            model_name='srtrackingdata',
            name='otherData2',
        ),
        migrations.RemoveField(
            model_name='srtrackingdata',
            name='otherData3',
        ),
        migrations.AddField(
            model_name='catrackingdata',
            name='rawJson',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='rawJson',
            field=models.JSONField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catrackingdata',
            name='trackingTransporte',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
