# Generated by Django 5.0.4 on 2024-11-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0006_alter_catrackingdata_rawjson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srtrackingdata',
            old_name='trackingDistribucion',
            new_name='tracking_id',
        ),
        migrations.AddField(
            model_name='order',
            name='tipo',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='checkout_observation',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='pedido',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='planned_date',
            field=models.DateField(default='2024-09-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='reference',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='seller',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='status',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='tipo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='srtrackingdata',
            name='title',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='trackingDistribucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
