# Generated by Django 5.0.4 on 2024-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('admin', 'Admin'), ('client', 'Client')], default='employee', max_length=20),
        ),
    ]
