# Generated by Django 5.0.4 on 2024-10-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_remove_company_address_remove_company_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Empleado'), ('client', 'Cliente')], default='employee', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserAttribute',
        ),
    ]
